"""add rank_id to employee

Revision ID: 8d0363f15064
Revises: 8d39b9349f56
Create Date: 2025-07-08 20:06:18.209050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d0363f15064'
down_revision: Union[str, Sequence[str], None] = '8d39b9349f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('rank_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'ranks', ['rank_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'rank_id')
    # ### end Alembic commands ###
