"""add leave table

Revision ID: ab2f1c414307
Revises: b71c898d4c34
Create Date: 2025-07-10 12:04:29.076539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab2f1c414307'
down_revision: Union[str, Sequence[str], None] = 'b71c898d4c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'employees', 'ranks', ['rank_id'], ['id'])
    op.alter_column('leaves', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.drop_constraint(None, 'leaves', type_='foreignkey')
    op.drop_constraint(None, 'leaves', type_='foreignkey')
    op.create_foreign_key(None, 'leaves', 'users', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'leaves', 'users', ['approved_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leaves', type_='foreignkey')
    op.drop_constraint(None, 'leaves', type_='foreignkey')
    op.create_foreign_key(None, 'leaves', 'users', ['approved_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'leaves', 'users', ['employee_id'], ['id'], ondelete='CASCADE')
    op.alter_column('leaves', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    # ### end Alembic commands ###
